apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: student-api
data:
  DATABASE_HOST: postgres
  DATABASE_PORT: "5432"
  DATABASE_NAME: studentdb

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-api
  namespace: student-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-api
  template:
    metadata:
      labels:
        app: student-api
    spec:
      initContainers:
        - name: migrate-db
          image: dipakrasal2009/sim-flask-api:latest
          command:
            - sh
            - -c
            - |
              echo "Testing DB connection..."
              until pg_isready -h postgres -p 5432 -U $POSTGRES_USER; do
                echo "waiting for db....";
                sleep 5;
              done
              echo "DB is ready.."
              #python3 migrate.py
              #python3 -m app.migrate
              #python -c "from app import create_app; from app.db import db; app = create_app(); exec('with app.app_context(): db.create_all()')"
              # python <<EOF
              #from app import create_app
#from app.db import db
#app = create_app()
#with app.app_context():
  #db.create_all()
    #EOF
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: POSTGRES_DB
              value: studentdb
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: DATABASE_HOST
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: DATABASE_PORT
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: DATABASE_NAME
      containers:
        - name: flask-api
          image: dipakrasal2009/sim-flask-api:latest
          ports:
            - containerPort: 5050  # <-- Flask must listen on 0.0.0.0:5050!
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: POSTGRES_DB
              value: studentdb
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: DATABASE_HOST
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: DATABASE_PORT
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: DATABASE_NAME

---
apiVersion: v1
kind: Service
metadata:
  name: student-api
  namespace: student-api
spec:
  type: NodePort
  selector:
    app: student-api
  ports:
    - port: 80
      targetPort: 5050  # <-- Must match your flask-api container port!

