apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-credentials-sync
  namespace: student-api
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore   # <-- CHANGED
    name: vault-backend
  target:
    name: db-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: db-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: db-credentials
        property: password

