apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: student-api
data:
  POSTGRES_DB: studentdb

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: student-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          command:
            - sh
            - -c
            - |
              echo "Testing DB connection..."
              until pg_isready -h postgres -p 5432 -U $POSTGRES_USER; do
                echo "Waiting for DB..."
                sleep 3
              done
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: POSTGRES_DB
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          emptyDir: {}   # For demo; in prod use PVC

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: student-api
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432

