apiVersion: v1
kind: Service
metadata:
  name: student-api-service
  namespace: student-api
spec:
  selector:
    app: student-api-with-db
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort

