version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: studentdb
    ports:
      - "5432:5432"

  api:
    build: .
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: studentdb
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: studentdb
    ports:
      - "5050:5050"

