apiVersion: v1
kind: Namespace
metadata:
  name: student-api
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: student-db-config
  namespace: student-api
data:
  POSTGRES_DB: students
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: student-db-secrets
  namespace: student-api
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: student-db-secret
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: secret/student-db
        property: username
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: secret/student-db
        property: password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-db
  namespace: student-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-db
  template:
    metadata:
      labels:
        app: student-db
    spec:
      nodeSelector:
        type: database
      containers:
        - name: postgres
          image: postgres:14
          #image: dipakrasal2009/postgres:latest
          envFrom:
            - configMapRef:
                name: student-db-config
            - secretRef:
                name: student-db-secret
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: student-db
  namespace: student-api
spec:
  selector:
    app: student-db
  ports:
    - port: 5432

