apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: student-db-secret
  namespace: student-api
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: student-db-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: student-db
        property: username
    - secretKey: password
      remoteRef:
        key: student-db
        property: password

