apiVersion: v1
kind: Namespace
metadata:
  name: student-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-database
  namespace: student-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-database
  template:
    metadata:
      labels:
        app: my-database
    spec:
      containers:
        - name: my-database-container
          image: postgres:15
          env:
            - name: POSTGRES_DB
              value: studentdb
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-storage
          emptyDir: {}  # Ephemeral; use PVC for persistence
---
apiVersion: v1
kind: Service
metadata:
  name: my-database-service
  namespace: student-api
spec:
  selector:
    app: my-database
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None  # Optional: makes it headless for DNS discovery

