apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: student-api
data:
  DATABASE_HOST: postgres
  DATABASE_PORT: "5432"
  DATABASE_NAME: studentdb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-api
  namespace: student-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-api
  template:
    metadata:
      labels:
        app: student-api
    spec:
      # ---------- Init-container: run migration ----------
      initContainers:
        - name: migrate-db
          image: dipakrasal2009/sre_bootcamp-api1:v27
          command: ["python", "-m", "app.migrate"]
          envFrom:
            - secretRef:
                name: db-credentials
            - configMapRef:
                name: api-config
      # ---------- Main API container ----------
      containers:
        - name: flask-api
          image: dipakrasal2009/sre_bootcamp-api1:v27
          ports:
            - containerPort: 5050
          envFrom:
            - secretRef:
                name: db-credentials
            - configMapRef:
                name: api-config
          #readinessProbe:
            #httpGet:
            # path: /healthcheck
            # port: 5050
            #initialDelaySeconds: 5
            #periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: student-api
  namespace: student-api
spec:
  type: NodePort
  selector:
    app: student-api
  ports:
    - port: 80
      targetPort: 5050

